parameters:
  host: ''
  pool: ''
  sign: false

jobs:
- job: ${{ parameters.host }}
  pool: ${{ parameters.pool }}
  steps:
  - ${{ if eq(parameters.sign, 'true') }}:
    - script: 'npm install -g esy@latest --unsafe-perm'
      displayName: 'Installing deps'
  - ${{ if eq(parameters.sign, 'false') }}:
    - script: 'sudo npm install -g esy@latest --unsafe-perm'
      displayName: 'Installing deps'
  - script: esy i
    displayName: 'esy i'
  - script: esy x nasm --version
    displayName: 'Build and Dry run'
  - ${{ if eq(parameters.sign, 'false') }}:
      - bash: |
          cat >foo.s <<EOF
          mov eax, 0
          mov ebx, 0
          int 0x80
          EOF
          esy x nasm foo.s
      
  - ${{ if eq(parameters.sign, 'true') }}:
      - bash: |
          cat >foo.s <<EOF
          mov eax, 0
          mov ebx, 0
          int 0x80
          EOF
          C:/npm/prefix/node_modules/esy/_build/default/bin/esy.exe x nasm foo.s
      
